default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind

docker-build:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - artifacts/
  
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:

    - docker build --pull -t "wallex-back${CI_COMMIT_SHORT_SHA}" ./backend
    - docker push "wallex-back${CI_COMMIT_SHORT_SHA}"

  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - backend/Dockerfile
