apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
        - name: db
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: api
          image: m1xxos/wallexapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: DATABASE_URL
              value: postgres://myuser:mypassword@db-service/mydb

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: my-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
        - name: web
          image: m1xxos/wallex
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: REACT_APP_BACK_DOMAIN
              value: http://localhost:30000

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---

apiVersion: v1
kind: Service
metadata:
  name: web-service-bank
spec:
  type: NodePort
  selector:
    app: my-web-bank
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-bank
  template:
    metadata:
      labels:
        app: my-web-bank
    spec:
      containers:
        - name: web
          image: m1xxos/bankfront
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: REACT_APP_BACK_DOMAIN
              value: http://localhost:30000

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment-bank
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
